In [1]:
import pandas as pd

# Basically their are two type of data in pandas 
1. series (1D)
2. DataFrame (2D)

For the series

In [2]:
cars=pd.Series(["BMW","Mercedes","Porsche"])
cars

0         BMW
1    Mercedes
2     Porsche
dtype: object

In [3]:
color=pd.Series(["Grey","Black","Golden","Red"])
color

0      Grey
1     Black
2    Golden
3       Red
dtype: object

For the dataFrame

In [4]:
dataframe=pd.DataFrame({"Cars":cars,"Color":color})

In [5]:
dataframe

       Cars   Color
0       BMW    Grey
1  Mercedes   Black
2   Porsche  Golden
3       NaN     Red

In [6]:
cars[3]="Kabin"

In [7]:
cars

0         BMW
1    Mercedes
2     Porsche
3       Kabin
dtype: object

In [12]:
students=(["kabin","Sushnat","Remon","Aayush"])

In [13]:
roll=([1,2,3,4,])

In [14]:
roll

[1, 2, 3, 4]

In [15]:
att=pd.DataFrame({
    "Name":students,
    "Roll":roll
})

In [16]:
att

      Name  Roll
0    kabin     1
1  Sushnat     2
2    Remon     3
3   Aayush     4

In [17]:
car_sales=pd.read_csv("car-sales.csv")

In [18]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [19]:
car_sales.columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='object')

In [20]:
car_columns=car_sales.columns
car_columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='object')

In [21]:
car_columns[1]

'Colour'

 ## Describing Data

In [27]:
car_sales.info ()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Make           10 non-null     object
 1   Colour         10 non-null     object
 2   Odometer (KM)  10 non-null     int64
 3   Doors          10 non-null     int64
 4   Price          10 non-null     object
dtypes: int64(2), object(3)
memory usage: 532.0+ bytes

In [31]:
car_sales.isnull()

    Make  Colour  Odometer (KM)  Doors  Price
0  False   False          False  False  False
1  False   False          False  False  False
2  False   False          False  False  False
3  False   False          False  False  False
4  False   False          False  False  False
5  False   False          False  False  False
6  False   False          False  False  False
7  False   False          False  False  False
8  False   False          False  False  False
9  False   False          False  False  False

In [32]:
car_sales.describe()

       Odometer (KM)      Doors
count      10.000000  10.000000
mean    78601.400000   4.000000
std     61983.471735   0.471405
min     11179.000000   3.000000
25%     35836.250000   4.000000
50%     57369.000000   4.000000
75%     96384.500000   4.000000
max    213095.000000   5.000000

In [34]:
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price            object
dtype: object

In [35]:
len(car_sales)

10

In [36]:
car_sales.head()

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [37]:
car_sales.tail()

     Make Colour  Odometer (KM)  Doors      Price
5  Toyota  Green          99213      4  $4,500.00
6   Honda   Blue          45698      4  $7,500.00
7   Honda   Blue          54738      4  $7,000.00
8  Toyota  White          60000      4  $6,250.00
9  Nissan  White          31600      4  $9,700.00

## Selecting and Viewing data

In [38]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

## for .loc it refers to the location

In [41]:
car_sales.loc[3]

Make                    BMW
Colour                Black
Odometer (KM)         11179
Doors                     5
Price            $22,000.00
Name: 3, dtype: object

In [42]:
food=pd.Series(["momo","choclate","pizza","honey","Water"],index=[4,5,6,4,1])

In [43]:
food

4        momo
5    choclate
6       pizza
4       honey
1       Water
dtype: object

In [44]:
food.loc[4]

4     momo
4    honey
dtype: object

In [45]:
food.iloc[1]

'choclate'

In [46]:
car_sales.iloc[2]

Make                Toyota
Colour                Blue
Odometer (KM)        32549
Doors                    3
Price            $7,000.00
Name: 2, dtype: object

In [47]:
 car_sales[:3]

     Make Colour  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
1   Honda    Red          87899      4  $5,000.00
2  Toyota   Blue          32549      3  $7,000.00

In [49]:
car_sales.iloc[:3]

     Make Colour  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
1   Honda    Red          87899      4  $5,000.00
2  Toyota   Blue          32549      3  $7,000.00

In [50]:
car_sales.loc[:3]

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00

In [62]:
car_sales[car_sales["Make"]=="Toyota" ]

     Make Colour  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
2  Toyota   Blue          32549      3  $7,000.00
5  Toyota  Green          99213      4  $4,500.00
8  Toyota  White          60000      4  $6,250.00